"""Domain models used by the prompt management system."""

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class MessageRole(StrEnum):
    """Roles supported by the internal prompt message model."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    CONTEXT = "context"
    TOOL = "tool"


class BasePromptMessage(BaseModel):
    """Base model shared by every prompt message."""

    model_config = ConfigDict(frozen=True)

    content: str = Field(
        ...,
        min_length=1,
        description="Textual content carried by the message.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional structured information associated with the message.",
    )


class SystemMessage(BasePromptMessage):
    """System-level instructions defining assistant behavior."""

    role: Literal[MessageRole.SYSTEM] = MessageRole.SYSTEM


class UserMessage(BasePromptMessage):
    """Message submitted by the user."""

    role: Literal[MessageRole.USER] = MessageRole.USER


class AssistantMessage(BasePromptMessage):
    """Previous response generated by the assistant."""

    role: Literal[MessageRole.ASSISTANT] = MessageRole.ASSISTANT


class ContextMessage(BasePromptMessage):
    """Contextual information supplied to the language model."""

    role: Literal[MessageRole.CONTEXT] = MessageRole.CONTEXT
    source: str | None = Field(
        default=None,
        description="Optional identifier of the context source.",
    )


class ToolMessage(BasePromptMessage):
    """Information returned by an external tool or application service."""

    role: Literal[MessageRole.TOOL] = MessageRole.TOOL
    tool_name: str = Field(
        ...,
        min_length=1,
        description="Name of the tool that produced the message.",
    )


PromptMessage = (
    SystemMessage | UserMessage | AssistantMessage | ContextMessage | ToolMessage
)


class Prompt(BaseModel):
    """Immutable sequence of messages sent to an AI provider."""

    model_config = ConfigDict(frozen=True)

    messages: tuple[PromptMessage, ...] = Field(
        ...,
        min_length=1,
        description="Ordered messages that compose the complete prompt.",
    )
